/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121120-gc74181a04b-20250918"
#endif /* AVUTIL_FFVERSION_H */
